DROP DATABASE IF EXISTS PHONELAND;
CREATE DATABASE PHONELAND;
USE PHONELAND;

CREATE TABLE CLIENTE(
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY, 
NOMBRE VARCHAR (20) NOT NULL,
APELLIDOS VARCHAR (50) NOT NULL,
DIRECCION VARCHAR (100),
CIUDAD VARCHAR (20),
PROVINCIA VARCHAR (20),
CP VARCHAR (10),
TIPO_DE_CLIENTE VARCHAR (20), 
TELEFONO VARCHAR (15),
INGRESO DOUBLE);

CREATE TABLE VENTA(
ID_VENTA INT AUTO_INCREMENT PRIMARY KEY,
ID_CLIENTE INT,
ID_PRODUCTO INT,
UNIDADES INT,
FECHA_VENTAS DATE,
INDEX IDX_ID_CLIENTE (ID_CLIENTE),
INDEX IDX_ID_PRODUCTO (ID_PRODUCTO)
);

CREATE TABLE PRODUCTO(
ID_PRODUCTO INT AUTO_INCREMENT PRIMARY KEY,
ID_FABRICANTE INT,
INDEX IDX_ID_FABRICANTE (ID_FABRICANTE),
NOMBRE_PRODUCTO VARCHAR (30) NOT NULL,
PRECIO DOUBLE
);

CREATE TABLE FABRICANTE(
ID_FABRICANTE INT AUTO_INCREMENT PRIMARY KEY,
ID_PRODUCTO INT,
NOMBRE_FABRICANTE VARCHAR (30) NOT NULL,
GARANTIA INT
);

ALTER TABLE VENTA
ADD CONSTRAINT FK_ID_CLIENTE
FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTE (ID_CLIENTE);

ALTER TABLE VENTA
ADD CONSTRAINT FK_ID_PRODUCTO
FOREIGN KEY (ID_PRODUCTO)
REFERENCES PRODUCTO (ID_PRODUCTO);


